### ISSUE TITLE
13 errors and 4 failures when running tests with 'tox -e py27'

### ISSUE THREAD

**Issue by WyseNynja** [mitsuhiko/flask-openid#43]
```
$ tox -e py27
GLOB sdist-make: /Users/bwstitt/code/python-openid/setup.py
py27 inst-nodeps: /Users/bwstitt/code/python-openid/.tox/dist/python-openid-2.2.5.zip
py27 runtests: PYTHONHASHSEED='480270221'
py27 runtests: commands[0] | ./run_tests.sh
EE..................................................................................................................................................................................................EEEEE.................................................................................................................................E.......EEE..................................................................................................................................................................................E......................................................................................
----------------------------------------------------------------------
Ran 29 tests in 0.005s

OK
.......................................................................................................F.F....F.F..................................................................................E..........................................................
----------------------------------------------------------------------
Ran 17 tests in 0.006s

OK
.
======================================================================
ERROR: Failure: ImportError (No module named djopenid.server)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bwstitt/code/python-openid/.tox/py27/lib/python2.7/site-packages/nose/loader.py", line 420, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/bwstitt/code/python-openid/.tox/py27/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/bwstitt/code/python-openid/.tox/py27/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/bwstitt/code/python-openid/examples/djopenid/server/tests.py", line 3, in <module>
    from djopenid.server import views
ImportError: No module named djopenid.server

======================================================================
ERROR: Failure: TypeError (__init__() takes exactly 5 arguments (2 given))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bwstitt/code/python-openid/.tox/py27/lib/python2.7/site-packages/nose/loader.py", line 525, in makeTest
    return self._makeTest(obj, parent)
  File "/Users/bwstitt/code/python-openid/.tox/py27/lib/python2.7/site-packages/nose/loader.py", line 572, in _makeTest
    return self.loadTestsFromTestCase(obj)
  File "/Users/bwstitt/code/python-openid/.tox/py27/lib/python2.7/site-packages/nose/loader.py", line 496, in loadTestsFromTestCase
    return super(TestLoader, self).loadTestsFromTestCase(testCaseClass)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 56, in loadTestsFromTestCase
    loaded_suite = self.suiteClass(map(testCaseClass, testCaseNames))
TypeError: __init__() takes exactly 5 arguments (2 given)

======================================================================
ERROR: openid.test.test_consumer.TestDiffieHellmanResponseParameters.testAbsentMacKey
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bwstitt/code/python-openid/.tox/py27/lib/python2.7/site-packages/nose/case.py", line 381, in setUp
    try_run(self.inst, ('setup', 'setUp'))
  File "/Users/bwstitt/code/python-openid/.tox/py27/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/Users/bwstitt/code/python-openid/openid/test/test_consumer.py", line 1927, in setUp
    self.secret = cryptutil.randomString(self.session_cls.secret_size)
AttributeError: 'NoneType' object has no attribute 'secret_size'

======================================================================
ERROR: openid.test.test_consumer.TestDiffieHellmanResponseParameters.testAbsentServerPublic
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bwstitt/code/python-openid/.tox/py27/lib/python2.7/site-packages/nose/case.py", line 381, in setUp
    try_run(self.inst, ('setup', 'setUp'))
  File "/Users/bwstitt/code/python-openid/.tox/py27/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/Users/bwstitt/code/python-openid/openid/test/test_consumer.py", line 1927, in setUp
    self.secret = cryptutil.randomString(self.session_cls.secret_size)
AttributeError: 'NoneType' object has no attribute 'secret_size'

======================================================================
ERROR: openid.test.test_consumer.TestDiffieHellmanResponseParameters.testExtractSecret
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bwstitt/code/python-openid/.tox/py27/lib/python2.7/site-packages/nose/case.py", line 381, in setUp
    try_run(self.inst, ('setup', 'setUp'))
  File "/Users/bwstitt/code/python-openid/.tox/py27/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/Users/bwstitt/code/python-openid/openid/test/test_consumer.py", line 1927, in setUp
    self.secret = cryptutil.randomString(self.session_cls.secret_size)
AttributeError: 'NoneType' object has no attribute 'secret_size'

======================================================================
ERROR: openid.test.test_consumer.TestDiffieHellmanResponseParameters.testInvalidBase64MacKey
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bwstitt/code/python-openid/.tox/py27/lib/python2.7/site-packages/nose/case.py", line 381, in setUp
    try_run(self.inst, ('setup', 'setUp'))
  File "/Users/bwstitt/code/python-openid/.tox/py27/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/Users/bwstitt/code/python-openid/openid/test/test_consumer.py", line 1927, in setUp
    self.secret = cryptutil.randomString(self.session_cls.secret_size)
AttributeError: 'NoneType' object has no attribute 'secret_size'

======================================================================
ERROR: openid.test.test_consumer.TestDiffieHellmanResponseParameters.testInvalidBase64Public
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bwstitt/code/python-openid/.tox/py27/lib/python2.7/site-packages/nose/case.py", line 381, in setUp
    try_run(self.inst, ('setup', 'setUp'))
  File "/Users/bwstitt/code/python-openid/.tox/py27/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/Users/bwstitt/code/python-openid/openid/test/test_consumer.py", line 1927, in setUp
    self.secret = cryptutil.randomString(self.session_cls.secret_size)
AttributeError: 'NoneType' object has no attribute 'secret_size'

======================================================================
ERROR: Failure: ImportError (No module named lxml)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bwstitt/code/python-openid/.tox/py27/lib/python2.7/site-packages/nose/loader.py", line 420, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/bwstitt/code/python-openid/.tox/py27/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/bwstitt/code/python-openid/.tox/py27/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/bwstitt/code/python-openid/openid/test/test_examples.py", line 10, in <module>
    import twill.commands
  File "/Users/bwstitt/code/python-openid/.tox/py27/lib/python2.7/site-packages/twill/__init__.py", line 52, in <module>
    from shell import TwillCommandLoop
  File "/Users/bwstitt/code/python-openid/.tox/py27/lib/python2.7/site-packages/twill/shell.py", line 9, in <module>
    from twill import commands, parse, __version__
  File "/Users/bwstitt/code/python-openid/.tox/py27/lib/python2.7/site-packages/twill/commands.py", line 7, in <module>
    from lxml import html
ImportError: No module named lxml

======================================================================
ERROR: openid.test.test_fetchers.test_fetcher
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bwstitt/code/python-openid/.tox/py27/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_fetcher() takes exactly 3 arguments (0 given)

======================================================================
ERROR: openid.test.test_fetchers.run_fetcher_tests
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bwstitt/code/python-openid/.tox/py27/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: run_fetcher_tests() takes exactly 1 argument (0 given)

======================================================================
ERROR: openid.test.test_fetchers.test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bwstitt/code/python-openid/.tox/py27/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/bwstitt/code/python-openid/openid/test/test_fetchers.py", line 211, in test
    server = HTTPServer((host, port), FetcherTestHandler)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 420, in __init__
    self.server_bind()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
gaierror: [Errno 8] nodename nor servname provided, or not known

======================================================================
ERROR: Failure: TypeError (__init__() takes exactly 4 arguments (2 given))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bwstitt/code/python-openid/.tox/py27/lib/python2.7/site-packages/nose/loader.py", line 525, in makeTest
    return self._makeTest(obj, parent)
  File "/Users/bwstitt/code/python-openid/.tox/py27/lib/python2.7/site-packages/nose/loader.py", line 572, in _makeTest
    return self.loadTestsFromTestCase(obj)
  File "/Users/bwstitt/code/python-openid/.tox/py27/lib/python2.7/site-packages/nose/loader.py", line 496, in loadTestsFromTestCase
    return super(TestLoader, self).loadTestsFromTestCase(testCaseClass)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 56, in loadTestsFromTestCase
    loaded_suite = self.suiteClass(map(testCaseClass, testCaseNames))
TypeError: __init__() takes exactly 4 arguments (2 given)

======================================================================
ERROR: Failure: TypeError (__init__() takes exactly 4 arguments (2 given))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bwstitt/code/python-openid/.tox/py27/lib/python2.7/site-packages/nose/loader.py", line 525, in makeTest
    return self._makeTest(obj, parent)
  File "/Users/bwstitt/code/python-openid/.tox/py27/lib/python2.7/site-packages/nose/loader.py", line 572, in _makeTest
    return self.loadTestsFromTestCase(obj)
  File "/Users/bwstitt/code/python-openid/.tox/py27/lib/python2.7/site-packages/nose/loader.py", line 496, in loadTestsFromTestCase
    return super(TestLoader, self).loadTestsFromTestCase(testCaseClass)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 56, in loadTestsFromTestCase
    loaded_suite = self.suiteClass(map(testCaseClass, testCaseNames))
TypeError: __init__() takes exactly 4 arguments (2 given)

======================================================================
FAIL: Check that when an OpenID 1 response exceeds the OpenID 1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bwstitt/code/python-openid/openid/test/test_server.py", line 636, in test_id_res_OpenID1_exceeds_limit
    self.failIf(response.renderAsForm())
AssertionError: True is not false

======================================================================
FAIL: Check that when an OpenID 2 response exceeds the OpenID 1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bwstitt/code/python-openid/openid/test/test_server.py", line 563, in test_id_res_OpenID2_POST
    self.failUnless(response.renderAsForm())
AssertionError: False is not true

======================================================================
FAIL: test_browserWithReturnTo_OpenID1_exceeds_limit (openid.test.test_server.TestProtocolError)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bwstitt/code/python-openid/openid/test/test_server.py", line 106, in test_browserWithReturnTo_OpenID1_exceeds_limit
    self.failUnless(e.whichEncoding() == server.ENCODE_URL)
AssertionError: False is not true

======================================================================
FAIL: test_browserWithReturnTo_OpenID2_POST (openid.test.test_server.TestProtocolError)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bwstitt/code/python-openid/openid/test/test_server.py", line 87, in test_browserWithReturnTo_OpenID2_POST
    self.failUnless(e.whichEncoding() == server.ENCODE_HTML_FORM)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 815 tests in 1.632s

FAILED (errors=13, failures=4)
ERROR: InvocationError: '/Users/bwstitt/code/python-openid/run_tests.sh'
_______________________________________________________ summary ________________________________________________________
ERROR:   py27: commands failed
```

Might be worth setting up travis-ci or something similar to automate test runs

**Comment by puiterwijk** [comment]
Hi, thanks for reporting this.
Please note though that all of these errors are in python-openid, and not in flask-openid.

For python-openid, please check https://github.com/openid/python-openid.

**Comment by WyseNynja** [comment]
Oops. Too many tabs open. Thanks!
